server.port=8080
spring.application.name=shareit-gateway
shareit-server.url=http://localhost:9090
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
logging.level.ru.practicum.shareit=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG